services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: main
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      API_HOST: image_service
      IS_TEST: True
      REDIS_HOST: redis
    networks:
      - internal
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    networks:
      - internal
    environment:
      HOST: 0.0.0.0
      NUXT_PUBLIC_API_BASE: "http://localhost:8000"
      PORT: 3000
      NODE_ENV: production
    restart: unless-stopped

  migrate:
    profiles: ["tools"]
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migrate
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_USER: postgres
    networks:
      - internal
    depends_on:
      - postgres
    restart: "no"

  runner:
    profiles: ["tools"]
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_USER: postgres
    networks:
      - internal
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    networks:
      - internal


networks:
  internal:
    driver: bridge

volumes:
  pgdata: