"""add_price_to_order

Revision ID: 9516fb3000d8
Revises: 6b8e79a754c3
Create Date: 2026-05-27 18:37:19.832885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9516fb3000d8'
down_revision: Union[str, Sequence[str], None] = '6b8e79a754c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('orders', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('orders_product_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('orders', 'product_snapshot')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
