server {
    listen 80;
    #server_name keramovibor.ru www.keramovibor.ru;

    client_max_body_size 15M;

    access_log off;
    error_log /var/log/nginx/error.log warn;

    # 1. КОРЕНЬ ФРОНТЕНДА (Nginx будет искать index.html здесь)
    root /var/www/frontend;
    index index.html;


    # 3. Фотографии товаров
    location /media/ {
        alias /var/www/media/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        access_log off;
    }

    # 4. Проксирование к FastAPI
    location /api/ {
        proxy_pass http://api:8000;
        include /etc/nginx/snippets/proxy_common.conf;
    }
    location /api/ws/ {
        proxy_pass http://api:8000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
    # 5. Кеширование системных файлов Nuxt
    location /_nuxt/ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }

    # 6. ГЛАВНОЕ ПРАВИЛО SPA
    # Если файла нет на диске, Nginx не выдает 404, а отдает index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
        deny all;
    }
}